version: '3.4'

services:
  solidslackbridge:
    image: solidslackbridge
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
      - 8080:8080
    networks:
      - ssb
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    networks:
      - ssb
networks:
  ssb: