version: '3.9'

services:
  solidslackbridge:
    image: solidslackbridge
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file: .env
    # environment:
    #   NODE_ENV: production
    ports:
      - 8000:8000
      - 8080:8080